# Dataset paths
train: /home/ziv/workspace/Mosquito_Supermodel/benchmark/Images
val: /home/ziv/workspace/Mosquito_Supermodel/benchmark/Images

# Number of classes (1 in this case for mosquitoes)
nc: 1
names: ['mosquito']

# Hyperparameter tuning
epochs: 10
batch: 128
lr0: 0.001
optimizer: Adam


