paths:
  image_path: "src/tests/images"       # Replace with the actual image folder path
  annotation_path: "src/tests/labels" # Replace with the actual annotations folder path
  save_path: "src/tests/plots_figure1"    # Replace with the folder to save plots


loss_figure:
  csv_path: "/home/wildmosquit0/workspace/weights/mosquitoes/exp1_less_crop_2002/results.csv"
  save_folder: "/home/wildmosquit0/git/Mosquito_Supermodel/src/figure/traning_data"


case_study:
  model_path: /home/wildmosquit0/workspace/weights/sahi_l_1_more_300e_200.pt
  base_dir: /home/wildmosquit0/workspace/data/model_exp/setups/seperate
  yaml_template_path: "/home/wildmosquit0/git/val.yaml"
  save_dir: /home/wildmosquit0/workspace/projects/supermodel/figures/figure_4_banch mark
  
