average_visits:
  filter_time_intervals: 10
  fps: 6
  interval_unit: minutes
  time_intervals: 1
  use_track_id: true
duration:
  fps: 4
heatmap:
  grid_size: 30
  image_path: /home/bohbot/workspace/projects/Gleb/new_cam/track
  min_count: 1
  true_axis: true
input_csv: /home/bohbot/workspace/projects/Gleb/new_cam/track/results.csv
output_dir: /home/bohbot/workspace/projects/Gleb/new_cam
plotxy:
  id_OR_class: track_id
  treatment_or_rep: image_name
  true_axis: true
task:
  average_visits: true
  duration: false
  heatmap: true
  plotxy: true
