average_visits:
  filter_time_intervals: 10
  fps: 15
  interval_unit: minutes
  time_intervals: 1
  use_track_id: true
duration:
  fps: 4
heatmap:
  grid_size: 30
  image_path: /home/bohbot/workspace/project/Dborneol/track
  min_count: 1
  true_axis: true
input_csv: /home/bohbot/workspace/project/Dborneol/all_crop/merged_filtered_data.csv
output_dir: /home/bohbot/workspace/project/23.04/crop_test
plotxy:
  id_OR_class: track_id
  treatment_or_rep: treatment
  true_axis: true
task:
  average_visits: true
  duration: false
  heatmap: true
  plotxy: true
