average_visits:
  filter_time_intervals: 10
  fps: 15
  interval_unit: minutes
  time_intervals: 1
duration:
  fps: 4
heatmap:
  grid_size: 30
  image_path: /home/bohbot/workspace/project/wt/track/
  min_count: 1
  true_axis: true
input_csv: /home/bohbot/workspace/project/wt/track/results.csv
output_dir: /home/bohbot/workspace/project/wt/results_t
plotxy:
  id_OR_class: track_id
  treatment_or_rep: treatment
  true_axis: true
task:
  average_visits: true
  duration: false
  heatmap: false
  plotxy: true
