heatmap:
  grid_size: 30
  image_path: /home/ziv/Downloads/mosqs/test_1/frames
  min_count: 1
  true_axis: true
input_csv: /home/ziv/Downloads/mosqs/test_1/results.csv
output_dir: /home/ziv/Downloads/mosqs/test_1
plotxy:
  id_OR_class: class
  treatment_or_image_name: image_name
  true_axis: true
settings:
  filter_time_intervals: 15
  fps: 1
  interval_unit: minute
  stat: sum
  time_intervals: 1
  treatment_or_image_name: treatment
  use_track_id: true
task:
  distance: true
  duration: true
  heatmap: true
  plotxy: true
  visits: true
