heatmap:
  grid_size: 30
  image_path: /home/bohbot/workspace/projects/test_sahi/frames
  min_count: 1
  true_axis: true
input_csv: /home/bohbot/workspace/projects/test_sahi/results.csv
output_dir: /home/bohbot/workspace/projects/test_sahi
plotxy:
  id_OR_class: class
  treatment_or_image_name: image_name
  true_axis: true
settings:
  filter_time_intervals: 16
  fps: 15
  interval_unit: minutes
  stat: mean
  time_intervals: 1
  treatment_or_image_name: treatment
  use_track_id: true
task:
  distance: true
  duration: true
  heatmap: false
  plotxy: true
  visits: true



yolo track model=/home/bohbot/workspace/weight/nectar.pt source=/home/bohbot/workspace/images/albo_date save_txt=true line_width=1 conf=0.7