input_csv: "src/tests/arad_roi_results.csv"
output_dir: "/home/bohbot/Evyatar/git/Mosquito_Supermodel/src/datasets/test"

task:
  plotxy: true
  average_visits: true
  duration: true

plotxy:
  id_OR_class: "track_id" # "track_id or label" 
  teratment_or_rep: "image_name" # "treatment or image_name"
  true_axis: true 

average_visits: 
  time_intervals: 60
  interval_unit: "seconds" # seconds or minutes
  fps: 3
  filter_time_intervals: 27

duration: 
  fps: 4