input_csv: "src/datasets/test/slice/results.csv"
output_dir: "src/datasets/test"

task:
  plotxy: true
  average_visits: True
  duration: False

plotxy:
  id_OR_class: "track_id" # "track_id or label" 
  teratment_or_rep: "image_name" # "treatment or image_name"
  true_axis: true 

average_visits: 
  time_intervals: 3
  interval_unit: "seconds" # seconds or minutes
  fps: 29
  filter_time_intervals: 27

duration: 
  fps: 4