average_visits:
  filter_time_intervals: 27
  fps: 15
  interval_unit: minutes
  time_intervals: 1
duration:
  fps: 4
heatmap:
  grid_size: null
  image_path: /home/wildmosquit0/workspace/data/Neta/Predict/shortened_control_1_first_frame.jpg
  min_count: null
  true_axis: true
input_csv: /home/wildmosquit0/workspace/data/Neta/Predict/results.csv
output_dir: /home/wildmosquit0/workspace/data/Neta
plotxy:
  id_OR_class: track_id
  treatment_or_rep: image_name
  true_axis: trues
task:
  average_visits: false
  duration: false
  heatmap: true
  plotxy: false
