average_visits:
  filter_time_intervals: 1440
  fps:  0.05
  interval_unit: minutes
  time_intervals: 180
duration:
  fps: 4
heatmap:
  grid_size: null
  image_path: /home/wildmosquit0/git/Mosquito_Supermodel/src/example/output/track/2023-07-07_10-47-35_first_frame.jpg
  min_count: null
  true_axis: true
input_csv: /home/bohbot/workspace/projects/neta/Predict
output_dir: /home/bohbot/workspace/projects/neta
plotxy:
  id_OR_class: track_id
  teratment_or_rep: treatment
  true_axis: true
task:
  average_visits: true
  duration: false
  heatmap: true
  plotxy: true
