average_visits:
  filter_time_intervals: 27
  fps: 2
  interval_unit: seconds
  time_intervals: 1
duration:
  fps: 4
heatmap:
  grid_size: null
  image_path: /home/wildmosquit0/workspace/projects/Arad/data/13_1_first_frame.jpg
  min_count: null
  true_axis: true
input_csv: /home/wildmosquit0/workspace/projects/Arad/data/
output_dir: /home/wildmosquit0/workspace/projects/Arad/figures
PlotXY:
  id_OR_class: track_id
  teratment_or_rep: image_name
  true_axis: trues
task:
  average_visits: false
  duration: false
  heatmap: true
  plotxy: false
