images_dir: /home/bohbot/workspace/images/or49/trim
model:
  conf_threshold: 0.5
  iou_threshold: 0.5
  object_size: big
  task: track
  vid_stride: 2
  weights: /home/bohbot/Evyatar/runs/detect/test_caht_parametrs2/weights/last.pt
output_dir: /home/bohbot/workspace/project/KO49
sahi:
  overlap_ratio: 0.2
  slice_size: 640
  track: true
save_animations: true
