images_dir: /home/wildmosquit0/workspace/data/model_exp/peers/3-2-2023_rep2_cropped_m.mp4
model:
  conf_threshold: 0.3
  iou_threshold: 0.1
  object_size: small
  task: slice
  vid_stride: 1
  weights: /home/wildmosquit0/workspace/weights/mosquitoes/exp1_less_crop_2002.pt
output_dir: /home/wildmosquit0/workspace/test_infer
sahi:
  overlap_ratio: 0.2
  slice_size: 640
  track: true
save_animations: true
