model: 
    weights: "best.pt"
    task: "track"
    conf_threshold: 0.2
    iou_threshold: 0.2
    vid_stride: 5

images_dir: "/home/bohbot/Evyatar/runs/track_test"
output_dir: "src/datasets/test"
save_animations: true