images_dir: /home/bohbot/workspace/projects/old_ODR/raw

model:
  conf_threshold: 0.5
  iou_threshold: 0.5
  task: slice
  vid_stride: 500
  weights: /home/bohbot/Evyatar/runs/detect/1000_each/weights/last.pt

output_dir: /home/bohbot/workspace/projects/test_1

sahi:
  overlap_ratio: 0.2
  slice_size: 800
  track: true

change_analyze_conf: true
save_animations: true