images_dir: /home/bohbot/Evyatar/exp/Joni_showoff/full movies
model:
  conf_threshold: 0.2
  iou_threshold: 0.2
  object_size: big
  task: predict
  vid_stride: 1
  weights: /home/bohbot/Evyatar/runs/detect/BFv112/weights/best.pt
output_dir: /home/bohbot/Evyatar/exp/Joni_showoff
sahi:
  overlap_ratio: 0.2
  slice_size: 640
  track: false
save_animations: true
