model: 
    weights: "https://drive.google.com/file/d/197Loxax03ptQBNzg8UvKNvfKAWLRCzaC/view?usp=drive_link"
    task: "track"
    conf_threshold: 0.2
    iou_threshold: 0.2
    vid_stride: 5

images_dir: "src/datasets/croped_movies/14"
output_dir: "src/datasets/croped_movies/14"
save_animations: true