images_dir: /home/bohbot/workspace/images/Gleb/v_cropped.mp4
model:
  conf_threshold: 0.2
  iou_threshold: 0.2
  object_size: big
  task: track
  vid_stride: 5
  weights: /home/bohbot/Evyatar/runs/detect/test_caht_parametrs2/weights/last.pt
output_dir: /home/bohbot/workspace/projects/Gleb
sahi:
  overlap_ratio: 0.2
  slice_size: 640
  track: true
save_animations: true
