images_dir: /home/bohbot/workspace/images/borneol
model:
  conf_threshold: 0.5
  iou_threshold: 0.5
  object_size: Big
  task: track
  vid_stride: 2
  weights:  /home/bohbot/Evyatar/runs/detect/test_caht_parametrs2/weights/last.pt
output_dir: /home/bohbot/workspace/projet/wt
sahi:
  overlap_ratio: 0.2
  slice_size: 640
  track: false
save_animations: true