images_dir: /home/ziv/Downloads/mosqs/Images-20250708T091042Z-1-001/Images

model:
  conf_threshold: 0.5
  iou_threshold: 0.5
  task: track
  vid_stride: 200
  weights: /home/ziv/Downloads/mosqs/MosquitoDetector_2.pt

output_dir: /home/ziv/Downloads/mosqs/test_1

sahi:
  overlap_ratio: 0.2
  save_animations: false
  slice_size: 640
  track: false

change_analyze_conf: true
save_animations: true