images_dir: /home/wildmosquit0/workspace/projects/Neta/Trap/movies
model:
  conf_threshold: 0.7
  iou_threshold: 0.5
  object_size: big
  task: predict
  vid_stride: 5000
  weights: /home/wildmosquit0/workspace/weights/mosquitoes/nectar.pt
output_dir: /home/wildmosquit0/workspace/projects/Neta/Trap
sahi:
  overlap_ratio: 0.2
  slice_size: 640
  track: true
save_animations: false
