model:
    weights: /home/wildmosquit0/git/bestModel/test_different_models/sahi_l_1_more_300e_200.pt
    task: track
    conf_threshold: 0.2
    iou_threshold: 0.2
    vid_stride: 5
sahi:
    slice_size: 640
    overlap_ratio: 0.2
images_dir: /home/wildmosquit0/git/model_exp/peers/IMG_4078.mp4
output_dir: src/datasets
save_animations: true
