images_dir: /home/wildmosquit0/workspace/data/Neta/short_vids copy
model:
  conf_threshold: 0.2
  iou_threshold: 0.2
  object_size: Big
  task: Predict
  vid_stride: 10
  weights:  /home/wildmosquit0/workspace/weights/mosquitoes/exp1_less_crop_2002/weights/best.pt
output_dir: /home/wildmosquit0/workspace/data/Neta
sahi:
  overlap_ratio: 0.2
  slice_size: 640
  track: false
save_animations: false