define_roi:
  folder_path: /home/bohbot/workspace/projects/test_1/frames  # This is a directory
  csv_path: /home/bohbot/workspace/projects/test_1/results.csv
  output_dir: /home/bohbot/workspace/projects/test_1
  get_inner_roi: true
  choose_frame_for_video: 1
