define_roi:
  folder_path: /home/bohbot/workspace/project/or49/track  # This is a directory
  csv_path: /home/bohbot/workspace/project/or49/track/results.csv
  output_dir: /home/bohbot/workspace/project/or49/track
  get_inner_roi: true
  choose_frame_for_video: 200
