define_roi:
  folder_path: /home/wildmosquit0/git/Mosquito_Supermodel/src/example/input/vids/vid3/  # This is a directory
  csv_path: /home/wildmosquit0/git/Mosquito_Supermodel/src/example/output/track/results.csv
  output_dir: /home/wildmosquit0/git/Mosquito_Supermodel/src/example/output/track
  get_inner_roi: true
  choose_frame_for_video: 200
