define_roi:
  folder_path: /home/wildmosquit0/workspace/projects/Arad/data  # This is a directory
  csv_path: /home/wildmosquit0/workspace/projects/Arad/data/results.csv
  output_dir: /home/wildmosquit0/workspace/projects/Arad/data
  get_inner_roi: true
  choose_frame_for_video: 200
